--- #YAML:1.0
name:               CLI-Framework
version:            0.01
abstract:           Build standardized, flexible, testable command-line applications
author:
    - Karl Erisman <karl.erisman@icainformatics.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Class::Inspector:     0
    Class::ISA:           0
    File::Spec:           0
    Getopt::Long::Descriptive:  0
    Term::ReadLine:       0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
